# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Daylist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daylist
  pod 'SnapKit', '~> 5.0.1'
  pod 'Then', '~> 2.7.0'


  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'
  
  # Others
  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 7.0'
  pod 'UITextView+Placeholder'
  pod 'SwiftSoup'

end
